### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#139]
In order to facilitate development, let's set up continuous deployment. Depends on a good test suite.

**Comment by evz** [comment]
Breaking this down a bit: 

- [ ] **Make tests faster** Right now they take forever, mainly because there is a ton of setup that happens before each test. 
- [ ] **Finish figuring out CodeDeploy** Got a start on this earlier.
- [ ] **Write more tests** Test coverage is great for happy path style stuff. Would be great to test for more error conditions.

**Comment by evz** [comment]
Busing the testing checkpoints out into separate issues and closing.
