### ISSUE TITLE
AJC and Federal are stuck in training mode

### ISSUE THREAD

**Issue by fgregg** [datamade/dedupe-api#177]
When I click finish, I get spinner forever. On main page, the mode stills says train:

http://dedupeapi.datamade.us/training-run/?session_id=044fa856-9b35-427e-ab77-0e14234cb5f9
http://dedupeapi.datamade.us/training-run/?session_id=1517decf-a734-4680-b297-6ccc0dabcf07

**Comment by evz** [comment]
The federal lobbyist data seems to have been sorted out. When I looked this morning, the AJC data had failed because I had pulled this fix 65eb3619a6c20bbfa35de89844664c81db83aa69 but had not restarted the app to make it active (d'oh). So, it's blocking right now and probably will be for a while: 

![screen shot 2015-04-14 at 8 47 21 am](https://cloud.githubusercontent.com/assets/551491/7138031/40030a16-e283-11e4-91d9-8c3827b0ddf6.png)

If I remember from my local experiments, there were about 640,000 records that need to be blocked so, 100 seconds * 64 is not quite two hours.
